//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jsinh.Shopify.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jsinh.Shopify.Api.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}/admin/oauth/access_token.
        /// </summary>
        internal static string AccessTokenUrl {
            get {
                return ResourceManager.GetString("AccessTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key configuration &apos;shopify-dotnet-api-key&apos; key / value missing.
        /// </summary>
        internal static string ApiKeyNotFoundException {
            get {
                return ResourceManager.GetString("ApiKeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.myshopify.com/admin/oauth/authorize?client_id={1}&amp;scope={2}.
        /// </summary>
        internal static string AuthorizationUrl {
            get {
                return ResourceManager.GetString("AuthorizationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_id.
        /// </summary>
        internal static string ClientIdKeyword {
            get {
                return ResourceManager.GetString("ClientIdKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_secret.
        /// </summary>
        internal static string ClientSecretKeyword {
            get {
                return ResourceManager.GetString("ClientSecretKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string CodeKeyword {
            get {
                return ResourceManager.GetString("CodeKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        internal static string DefaultHttpClientContentType {
            get {
                return ResourceManager.GetString("DefaultHttpClientContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hmac.
        /// </summary>
        internal static string HmacKeyword {
            get {
                return ResourceManager.GetString("HmacKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopify-dotnet-api-key.
        /// </summary>
        internal static string KeyShopifyApiKey {
            get {
                return ResourceManager.GetString("KeyShopifyApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopify-dotnet-secret-key.
        /// </summary>
        internal static string KeyShopifyAppSecret {
            get {
                return ResourceManager.GetString("KeyShopifyAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .myshopify.com.
        /// </summary>
        internal static string MyShopifyDomain {
            get {
                return ResourceManager.GetString("MyShopifyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret key configuration &apos; shopify-dotnet-secret-key&apos; key /value missing.
        /// </summary>
        internal static string SecretKeyNotFoundException {
            get {
                return ResourceManager.GetString("SecretKeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shop.
        /// </summary>
        internal static string ShopKeyword {
            get {
                return ResourceManager.GetString("ShopKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop name configuration &apos;shopify-dotnet-shop-name&apos; key / value missing.
        /// </summary>
        internal static string ShopNameNotFoundException {
            get {
                return ResourceManager.GetString("ShopNameNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timestamp.
        /// </summary>
        internal static string TimestampKeyword {
            get {
                return ResourceManager.GetString("TimestampKeyword", resourceCulture);
            }
        }
    }
}
